### ISSUE TITLE
Add Admins

### ISSUE THREAD

**Issue by amandaTesterman** [sobrien-banyan/Imma-chore#20]
## Overview
Add Christopher and Amanda as admins to the repo

**Comment by sobrien-banyan** [comment]
@amandaTesterman, I've tried to make you and Chris administrators. The GitHub docs are outdated. I've created an organization hoping that will be the solution. If you find a way to add people as admins let me know.

**Comment by sobrien-banyan** [comment]
Added @amandaTesterman @christopher-cialone as admins to project

**Comment by christopher-cialone** [comment]
I dont think that worked but im looking into a fix, my access hasn't been updated
