### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by sobrien-banyan** [sobrien-banyan/Imma-chore#4]
## Overview

Please update the readme.md file. Feel free to be creative. We can use the readme from the todo app as a guide.
https://github.com/sobrien-banyan/todo/blob/main/README.md

no screenshot

## Technical Notes

This link might be helpful https://www.makeareadme.com/

**Comment by amandaTesterman** [comment]
Added line for Devs: and then my name beneath it

**Comment by christopher-cialone** [comment]
added my name
